-- Learner donation payments (eLearning R50)
-- Run this in Supabase SQL editor.
-- This table is intended to be accessed ONLY via the Cloudflare Worker (service role),
-- not directly from the browser.

create table if not exists public.carissa_learner_payments (
  id bigint generated by default as identity primary key,

  class_name text not null,
  learner_number integer not null,
  learner_username text not null,

  surname text not null,
  firstname text not null,

  amount integer not null default 50,
  paid_to text not null check (paid_to in ('office','lerato','eft')),
  paid_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (class_name, learner_number)
);

create index if not exists carissa_learner_payments_class_idx
  on public.carissa_learner_payments (class_name);

create index if not exists carissa_learner_payments_username_idx
  on public.carissa_learner_payments (learner_username);

-- Lock it down (Worker service-role bypasses RLS; browser should have no access)
alter table public.carissa_learner_payments enable row level security;

revoke all on table public.carissa_learner_payments from anon;
revoke all on table public.carissa_learner_payments from authenticated;

-- Do NOT create policies for anon/authenticated.
-- All reads/writes should go through the Worker.
