-- SASAMS marks capture schema for the teacher portal
-- Run this file in the Supabase SQL editor.
-- Phase 1 covers:
--   - teacher capture
--   - autosave
--   - completeness
--   - submit for HOD review
-- Phase 1 does NOT sync back to SA-SAMS yet.

create extension if not exists pgcrypto;

-- ────────────────────────────────────────────────────────────────
-- Subject reference data
-- Load this from the SASAMS package file:
--   data/subjects_official_gr0_gr7.csv
-- Suggested field mapping:
--   official_subject_id <- SubjID
--   grade_no            <- GradeNo
--   subj_key            <- SubjectKey
--   name_english        <- NameEnglish
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_sasams_subjects (
  official_subject_id bigint primary key,
  grade_no integer not null,
  subj_key text,
  name_english text not null,
  report_label text,
  has_report_splits boolean default false,
  is_active boolean default true,
  created_at timestamptz default now()
);

create index if not exists carissa_sasams_subjects_grade_idx
  on public.carissa_sasams_subjects (grade_no, name_english);

-- ────────────────────────────────────────────────────────────────
-- Criteria / recording-sheet columns
-- Load this from the SASAMS package file:
--   data/criteria_recording_sheets_2026.csv
-- Suggested field mapping:
--   academic_year         <- 2026 (or the active year)
--   term_no               <- TermNo
--   grade_no              <- GradeNo
--   official_subject_id   <- SubjID
--   off_criterion_id      <- OffCriterionID
--   description           <- CriterionDescription
--   short_label           <- CriterionShortLabel
--   criterion_score_max   <- CriterionScoreMax
--   weighting_of_split_pct<- WeightingPct
--   sba_of_yearmark_pct   <- SBAofYearMarkPct
--   criterion_type        <- CriterionType
--   split_no              <- SplitNo
--   is_exam               <- IsExam
--   sort_order            <- SortOrder
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_sasams_criteria (
  id bigint generated by default as identity primary key,
  academic_year integer not null,
  term_no integer not null check (term_no between 1 and 4),
  grade_no integer not null,
  official_subject_id bigint not null references public.carissa_sasams_subjects(official_subject_id) on delete cascade,
  off_criterion_id bigint not null,
  description text not null,
  short_label text,
  criterion_score_max numeric(8,2) not null default 100,
  weighting_of_split_pct numeric(8,3),
  sba_of_yearmark_pct numeric(8,3),
  criterion_type text,
  split_no integer,
  is_exam boolean default false,
  sort_order integer,
  created_at timestamptz default now(),
  unique (academic_year, term_no, grade_no, official_subject_id, off_criterion_id)
);

create index if not exists carissa_sasams_criteria_lookup_idx
  on public.carissa_sasams_criteria (academic_year, term_no, grade_no, official_subject_id, sort_order);

-- ────────────────────────────────────────────────────────────────
-- Teacher batch state for a class / term / subject
-- One teacher keeps one batch per class, term, and subject.
-- status:
--   DRAFT      teacher still capturing
--   SUBMITTED  sent for HOD review
--   APPROVED   accepted by HOD
--   REJECTED   returned to teacher for edits
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_sasams_batches (
  id uuid primary key default gen_random_uuid(),
  academic_year integer not null,
  term_no integer not null check (term_no between 1 and 4),
  class_name text not null,
  grade_no integer not null,
  official_subject_id bigint not null references public.carissa_sasams_subjects(official_subject_id) on delete cascade,
  teacher_email text not null,
  teacher_name text,
  status text not null default 'DRAFT' check (status in ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
  submitted_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  hod_name text,
  hod_note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (academic_year, term_no, class_name, official_subject_id, teacher_email)
);

create index if not exists carissa_sasams_batches_teacher_idx
  on public.carissa_sasams_batches (teacher_email, class_name, term_no, academic_year);

create index if not exists carissa_sasams_batches_status_idx
  on public.carissa_sasams_batches (status, updated_at desc);

-- ────────────────────────────────────────────────────────────────
-- Learner marks inside a batch
-- learner_no is taken from the existing class list number in the portal.
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_sasams_marks (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.carissa_sasams_batches(id) on delete cascade,
  academic_year integer not null,
  term_no integer not null check (term_no between 1 and 4),
  class_name text not null,
  grade_no integer not null,
  official_subject_id bigint not null references public.carissa_sasams_subjects(official_subject_id) on delete cascade,
  off_criterion_id bigint not null,
  learner_no text not null,
  surname text not null,
  firstname text not null,
  raw_mark_entered numeric(8,2),
  raw_mark_max numeric(8,2) not null,
  mark_percent numeric(8,2),
  weighted_sba_pct numeric(8,3),
  comment text,
  teacher_email text,
  teacher_name text,
  status text not null default 'PENDING' check (status in ('PENDING','SUBMITTED','APPROVED','REJECTED')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (batch_id, off_criterion_id, learner_no)
);

create index if not exists carissa_sasams_marks_batch_idx
  on public.carissa_sasams_marks (batch_id, learner_no);

create index if not exists carissa_sasams_marks_lookup_idx
  on public.carissa_sasams_marks (academic_year, term_no, class_name, official_subject_id, teacher_email);

-- ────────────────────────────────────────────────────────────────
-- Optional view for quick teacher summaries
-- ────────────────────────────────────────────────────────────────
create or replace view public.carissa_sasams_capture_summary as
select
  b.id as batch_id,
  b.academic_year,
  b.term_no,
  b.class_name,
  b.grade_no,
  b.official_subject_id,
  s.name_english as subject_name,
  b.teacher_email,
  b.teacher_name,
  b.status,
  count(m.id) as captured_cells,
  max(b.updated_at) as last_updated_at,
  b.submitted_at,
  b.hod_name,
  b.hod_note
from public.carissa_sasams_batches b
left join public.carissa_sasams_subjects s
  on s.official_subject_id = b.official_subject_id
left join public.carissa_sasams_marks m
  on m.batch_id = b.id
group by
  b.id,
  b.academic_year,
  b.term_no,
  b.class_name,
  b.grade_no,
  b.official_subject_id,
  s.name_english,
  b.teacher_email,
  b.teacher_name,
  b.status,
  b.submitted_at,
  b.hod_name,
  b.hod_note;

-- ────────────────────────────────────────────────────────────────
-- RLS note
-- The current portal uses the Supabase anon key directly in the browser.
-- If you enable RLS on these tables, matching policies must be added first.
-- For the current internal setup, keep them without RLS until the secure
-- server-side marks workflow is introduced.
-- ────────────────────────────────────────────────────────────────
