-- Supabase schema for Carissa Tracker (assignments-focused)
-- This file is meant to be run in the Supabase SQL editor for the connected project.
-- It does NOT change the website UI; it only ensures the database tables exist.

-- ────────────────────────────────────────────────────────────────
-- Resources library
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  type text default 'link',
  subject text,
  grade_range text,
  folder text,
  description text,
  uploaded_by text default 'Admin',
  created_at timestamptz default now()
);

-- ────────────────────────────────────────────────────────────────
-- Assignments (Admin → Teacher → Learner tracking)
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_resource_assignments (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.carissa_resources(id) on delete cascade,
  class_name text not null,
  assign_type text default 'class',
  surname text not null,
  firstname text not null,
  assigned_by text default 'Admin',
  due_date date,
  notes text,
  status text default 'assigned',
  progress_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists carissa_resource_assignments_class_idx
  on public.carissa_resource_assignments (class_name);

create index if not exists carissa_resource_assignments_learner_idx
  on public.carissa_resource_assignments (class_name, surname, firstname);

-- ────────────────────────────────────────────────────────────────
-- Learner activity results (Learner → Teacher score feedback)
-- ────────────────────────────────────────────────────────────────
create table if not exists public.carissa_learner_activity_results (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.carissa_resource_assignments(id) on delete cascade,
  learner_username text not null,
  class_name text not null,
  surname text not null,
  firstname text not null,
  resource_id bigint references public.carissa_resources(id) on delete set null,
  result_status text default 'submitted',
  score integer default 0,
  max_score integer default 100,
  learner_notes text,
  submitted_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (assignment_id, learner_username)
);

create index if not exists carissa_learner_activity_results_assignment_idx
  on public.carissa_learner_activity_results (assignment_id);

create index if not exists carissa_learner_activity_results_learner_idx
  on public.carissa_learner_activity_results (class_name, surname, firstname);

-- ────────────────────────────────────────────────────────────────
-- RLS (IMPORTANT)
-- The tracker frontend uses the Supabase anon key directly.
-- If you enable RLS, you must create matching policies; otherwise the app cannot read/write.
-- For a private/internal tool you can keep RLS disabled on these tables.
-- ────────────────────────────────────────────────────────────────
-- alter table public.carissa_resources enable row level security;
-- alter table public.carissa_resource_assignments enable row level security;
--
-- Example permissive policies (use with care):
-- create policy "allow anon read resources"
--   on public.carissa_resources for select
--   to anon using (true);
--
-- create policy "allow anon write resources"
--   on public.carissa_resources for insert
--   to anon with check (true);
--
-- create policy "allow anon update resources"
--   on public.carissa_resources for update
--   to anon using (true) with check (true);
--
-- create policy "allow anon delete resources"
--   on public.carissa_resources for delete
--   to anon using (true);
--
-- create policy "allow anon read assignments"
--   on public.carissa_resource_assignments for select
--   to anon using (true);
--
-- create policy "allow anon write assignments"
--   on public.carissa_resource_assignments for insert
--   to anon with check (true);
--
-- create policy "allow anon update assignments"
--   on public.carissa_resource_assignments for update
--   to anon using (true) with check (true);
--
-- create policy "allow anon delete assignments"
--   on public.carissa_resource_assignments for delete
--   to anon using (true);
